[project]
name = "mrpowers-benchmarks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datafusion>=42.0.0",
    "getdaft>=0.3.13",
    "pandas>=2.2.3",
    "polars>=1.14.0",
]
